trigger: none
pr:
  - main

variables:
  - group: elarande-general-params
  - name: imageName
    value: transfer-to-ladok
  - name: dockerfilePath
    value: "$(Pipeline.Workspace)/github/Dockerfile"
  - name: tag
    value: "$(Build.SourceVersion)"

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/docker/build.yml@cet-iac
    parameters:
      runScan: false
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)

  - template: templates/test/npm-test.yml@cet-iac
  - template: templates/docker/push.yml@cet-iac
    parameters:
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)

  - template: templates/app-service/update-image.yml@cet-iac
    parameters:
      parametersFileName: $(parametersFileName)
      appName: $(appName)
      imageName: $(imageName)
      tag: $(tag)
      isApi: false
