trigger: none
pr: none

parameters:
- name: imageTag
  type: string
  displayName: New image tag in production

variables:
  - group: elarande-general-params
  - group: elarande-spoke1-prod
  - name: appName
    value: transfer-to-ladok-prod
  - name: imageName
    value: transfer-to-ladok
  - name: parametersFileName
    value: prod.parameters.json

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/app-service/update-image.yml@cet-iac
    parameters:
      parametersFileName: $(parametersFileName)
      appName: $(appName)
      imageName: $(imageName)
      tag: ${{ parameters.imageTag }}
      isApi: false
